export const meta = {
  name: 'vigil-arch-and-design',
  description: 'Architect + design-spec a native macOS Hikvision camera viewer (zero-dependency Swift)',
  phases: [
    { title: 'Specs', detail: '12 parallel spec + design authors' },
    { title: 'Contract', detail: 'reconcile into one API + file manifest contract' },
  ],
}

const LOG = '/home/user/camera/.build-progress.log'

const LOGGING_RULES = [
  '',
  '## MANDATORY PROGRESS LOGGING (you will be judged on this)',
  'You MUST append progress lines to the shared build log so the supervisor can follow you live.',
  'Use exactly this Bash form (single line, append only, never overwrite, never read the whole file):',
  '',
  '    echo "[$(date -u +%H:%M:%S)] AGENT_LABEL | <stage> | <short message>" >> ' + LOG,
  '',
  'Log at these five moments, minimum:',
  '  1. START      right after you read this assignment ("started, plan: ...")',
  '  2. RESEARCH   when you have finished deciding structure ("outline done, N sections")',
  '  3. HALFWAY    when roughly half the document is written ("wrote sections 1-N")',
  '  4. WRITTEN    immediately after the Write tool succeeds ("wrote <path>, <bytes> bytes")',
  '  5. DONE       last action before returning ("done, key decisions: ...")',
  'Keep each line under 160 characters. Never put newlines inside a log line.',
  'Replace AGENT_LABEL with the label given in your assignment header.',
].join('\n')

const SHARED = [
  '# PROJECT CONTEXT (read fully - you are one of many parallel authors)',
  '',
  'We are building **Vigil** - a native macOS application for viewing Hikvision IP cameras and NVRs',
  'on a local network.',
  '',
  'Repo root: /home/user/camera  (currently EMPTY except .git and docs/ - you are creating it from scratch)',
  '',
  '## Hard technical constraints (non-negotiable)',
  '- Language: **Swift 6**, strict concurrency. Target **macOS 14.0+** (Sonoma).',
  '  UI in **SwiftUI** with AppKit interop (NSViewRepresentable) where needed.',
  '- **ZERO external dependencies.** No SPM packages, no CocoaPods, no FFmpeg, no VLCKit, no GStreamer.',
  '  Only Apple system frameworks: Foundation, Network, SwiftUI, AppKit, AVFoundation, VideoToolbox,',
  '  CoreMedia, CoreVideo, Metal, MetalKit, CoreImage, AudioToolbox, Security (Keychain), OSLog,',
  '  Observation, Accelerate, UserNotifications, UniformTypeIdentifiers, AppIntents.',
  '  Rationale: must build on any Mac with Xcode, no network fetch, and we need total control of latency.',
  '- Therefore **we implement RTSP + RTP + SDP + H.264/H.265 bitstream handling ourselves in pure Swift**,',
  '  feeding VideoToolbox for hardware decode and AVSampleBufferDisplayLayer / Metal for display.',
  '- **Layering rule that MATTERS:** all protocol and parsing logic (RTSP messages, SDP, RTP',
  '  depacketization, NAL/bitstream parsing, ISAPI XML, discovery packet codecs, jitter-buffer math)',
  '  lives in **platform-independent, Foundation-only** targets so they compile and unit-test on',
  '  **Linux Swift 6.1** too - we actually run those tests in CI on Linux. Anything touching',
  '  VideoToolbox / AppKit / SwiftUI / Metal / Security / Network lives in separate macOS-only targets.',
  '  The pure layer must NOT use CoreMedia types (no CMTime, no CVPixelBuffer); it uses our own value',
  '  types (MediaTimestamp, EncodedFrame) at the boundary.',
  '- Build: **Swift Package Manager** package at repo root, plus a script that assembles a real',
  '  Vigil.app bundle, plus an XcodeGen project.yml for people who want an Xcode project.',
  '  No hand-written .pbxproj.',
  '',
  '## Module targets (fixed names - use these exactly)',
  'Platform-independent (Foundation only, Linux-testable):',
  '- VigilProtocols  - shared value types, errors, logging protocol, byte reader/writer, bit reader.',
  '- VigilRTSP       - RTSP message model + parser/serializer, Digest/Basic auth, SDP parser,',
  '                    RTSP session state machine (transport-agnostic: driven by injected bytes + clock).',
  '- VigilRTP        - RTP/RTCP parsing, H.264 (RFC 6184) + H.265 (RFC 7798) + AAC (RFC 3640) + G.711',
  '                    depacketizers, jitter/reorder buffer, framerate and bitrate statistics.',
  '- VigilBitstream  - Annex-B <-> length-prefixed conversion, SPS/PPS/VPS parsing (H.264 + H.265),',
  '                    resolution/fps/profile extraction, avcC/hvcC record building.',
  '- VigilISAPI      - Hikvision ISAPI request builders + lenient XML response parsers.',
  '                    URLSession IS available on Linux Foundation, so URLSession is allowed here.',
  '- VigilDiscovery  - SADP + ONVIF WS-Discovery packet encode/decode, CIDR/subnet enumeration math.',
  'macOS-only:',
  '- VigilTransport  - Network.framework TCP/UDP transports wiring the pure state machines to real',
  '                    sockets, TLS, keepalive timers, multicast.',
  '- VigilVideo      - VideoToolbox decode sessions, CMFormatDescription/CMSampleBuffer construction,',
  '                    frame pacing, decode-budget scheduler, HEVC/H.264 HW decode, audio playback.',
  '- VigilRender     - AVSampleBufferDisplayLayer view + Metal renderer (zoom/pan/digital-PTZ, colour',
  '                    adjust, overlays, cropping), NSViewRepresentable wrappers.',
  '- VigilCore       - app domain: camera model, Keychain credentials, stream controller/coordinator,',
  '                    recording (AVAssetWriter passthrough), snapshots, event centre, persistence.',
  '- VigilUI         - design system + all SwiftUI views and components.',
  '- Vigil           - executable target (@main App, menu bar, window management).',
  '',
  '## Product bar',
  'The design must feel like a **top-tier, award-winning Mac app**. Reference class: Raycast, Linear,',
  'Arc, Craft, CleanShot X, Things 3. Translucent materials, precise typography, restrained but',
  'delightful spring motion, keyboard-first, zero jank at 120 Hz. Functionality must be deep and',
  'complete, not a demo. Performance target: under 250 ms glass-to-glass latency on LAN; 16 simultaneous',
  '1080p substreams under about 35% CPU on Apple silicon via hardware decode and zero-copy paths.',
  '',
  '## YOUR JOB',
  'Write ONE markdown document (path given in your assignment) precise enough for an implementation',
  'agent to code from **without further research**. Be concrete: real wire formats, real byte offsets,',
  'real Apple API names and signatures, real numbers. Include Swift signatures and snippets where they',
  'pin down a decision. No hand-waving, no TODO, no "we could consider". Make decisions.',
  'Aim for a dense, long, complete document. Use tables and code blocks.',
  'Write the file with the Write tool. Then return a summary of at most 12 lines listing the key',
  'cross-cutting decisions OTHER agents must respect (this summary is fed to the contract author).',
  'Do NOT write any Swift source files - only your one markdown document.',
  LOGGING_RULES,
].join('\n')

const SPECS = [
  {
    key: 'architecture',
    path: 'docs/ARCHITECTURE.md',
    task: [
      'Author the system architecture document.',
      'Cover:',
      '- The full module/target graph with dependency arrows and why each edge exists.',
      '- The exact Package.swift contents (swift-tools-version 6.0, macOS 14 platform, all targets plus',
      '  test targets) and the mechanism that lets the pure targets build on Linux while macOS-only',
      '  targets are excluded there. SwiftPM has no per-platform target exclusion, so DECIDE the real',
      '  mechanism (e.g. a documented "swift build --target" subset for Linux CI, plus file-level',
      '  #if os(macOS) guards) and write it out.',
      '- The concurrency model: which types are actor, which are @MainActor, which are Sendable value',
      '  types; how the per-camera pipeline is an actor with a bounded frame queue; how backpressure and',
      '  cancellation propagate; the structured-concurrency task tree per camera; why we avoid GCD except',
      '  for the VideoToolbox callback hop; how we satisfy Swift 6 strict concurrency at every boundary.',
      '- The end-to-end data flow: discovery -> camera record -> RTSP session -> RTP depacketize ->',
      '  EncodedFrame -> VideoToolbox -> CVPixelBuffer -> Metal / AVSampleBufferDisplayLayer -> screen,',
      '  naming the exact type that crosses each boundary.',
      '- Error taxonomy and a retry/reconnect state machine with exponential backoff plus jitter',
      '  (give the state diagram and the timings).',
      '- Observability: OSLog categories, signposts, a per-stream stats struct, and how the pure layer',
      '  logs through an injected LoggerProtocol instead of importing OSLog.',
      '- Persistence strategy: JSON document in Application Support plus Keychain for secrets, atomic',
      '  writes, schema versioning and migration.',
      '- Testing strategy: what is unit-tested on Linux, what needs a Mac, and the design of a',
      '  **synthetic RTSP server + RTP generator test fixture** so the whole pure pipeline can be tested',
      '  end-to-end with no camera present. This fixture is important - specify its API in detail.',
      '- Repo directory layout; the build-script contract (Scripts/build-app.sh producing Vigil.app);',
      '  Info.plist keys needed (NSLocalNetworkUsageDescription, NSAppTransportSecurity with',
      '  NSAllowsLocalNetworking for plain-http ISAPI on LAN, LSMinimumSystemVersion, document types);',
      '  the entitlements file contents (App Sandbox decision, com.apple.security.network.client,',
      '  com.apple.developer.networking.multicast, user-selected files read-write) and hardened-runtime',
      '  notes. Justify the sandbox decision explicitly.',
      '- Repo-wide **Swift style rules** implementers must follow: file header format, access control,',
      '  naming, no force-unwrap outside tests, error handling style, doc comments on public API,',
      '  MARK sections, 110-column lines.',
    ].join('\n'),
  },
  {
    key: 'rtsp',
    path: 'docs/spec-rtsp.md',
    task: [
      'Author the RTSP client specification (module VigilRTSP).',
      'Cover:',
      '- RTSP 1.0 (RFC 2326) message grammar; exact request/response serialization including CSeq,',
      '  User-Agent, Session, Require, Content-Length.',
      '- The full method sequence OPTIONS -> DESCRIBE -> SETUP (per track) -> PLAY ->',
      '  GET_PARAMETER keepalive -> PAUSE -> TEARDOWN, with example wire dumps for a Hikvision',
      '  DS-2CD2xxx camera and for a DS-7608 NVR.',
      '- Authentication: Basic and **Digest (RFC 2617, MD5, qop=auth and the no-qop variant, nonce, nc,',
      '  cnonce, opaque, re-auth on 401 with a new nonce, stale=true)**. Give the exact string',
      '  construction for A1, A2 and response, and note that the URI in A2 must be the request URI.',
      '  Note that Hikvision sends: WWW-Authenticate: Digest realm="IP Camera(XXXXX)", nonce="...",',
      '  stale="FALSE". Specify that we must compute MD5 ourselves (no CryptoKit in the pure layer -',
      '  decide: implement MD5 in VigilProtocols, it is ~120 lines, and unit-test it against RFC vectors).',
      '- Transports: **TCP interleaved (RTP-over-RTSP, Transport: RTP/AVP/TCP;unicast;interleaved=0-1)**',
      '  as the default, and the dollar-sign framing format (magic byte 0x24, channel byte, 16-bit',
      '  big-endian length) including how to resynchronize after corruption and how to demux interleaved',
      '  media frames from RTSP responses arriving on the SAME socket. Also UDP unicast as a secondary',
      '  path with port pairing and keepalive, and RTSP-over-TLS (rtsps, port 322).',
      '- SDP parsing (RFC 4566 plus RFC 3984/6184 fmtp): m= lines, a=control with absolute vs relative',
      '  URL resolution against Content-Base / Content-Location / request URI (spell out the precedence',
      '  rules exactly), a=rtpmap, a=fmtp with sprop-parameter-sets (H.264, base64 SPS,PPS) and',
      '  sprop-vps / sprop-sps / sprop-pps (H.265), a=range, a=framerate, and the Hikvision extras',
      '  a=Media_header and a=appversion that must be ignored gracefully.',
      '- RTP-Info header parsing (url=, seq=, rtptime=) and how it seeds presentation time.',
      '- Hikvision URL conventions as a table with which firmware generation uses which:',
      '  rtsp://user:pass@host:554/Streaming/Channels/101 (channel*100 + stream),',
      '  /Streaming/Channels/{ch}0{stream} for NVRs, /Streaming/tracks/101,',
      '  legacy /h264/ch1/main/av_stream and /mpeg4/ch1/sub/av_stream, and the ISAPI playback URL',
      '  rtsp://host/Streaming/tracks/101?starttime=20240101T000000Z&endtime=...',
      '- Playback control: PLAY with Range: clock=20240101T000000Z-, the Scale header for',
      '  fast-forward and reverse, RTCP-based progress, and the Rate-Control: no header used for',
      '  gapless seeking of recorded video. Also frame-step behaviour.',
      '- The **transport-agnostic state machine API**: define RTSPSessionMachine as a pure type driven by',
      '  ingest(bytes) returning events and step(now) returning actions, where an action is',
      '  send(Data) / setTimer / emitTrack / fail, so it is 100% unit-testable with no sockets.',
      '  Give the complete public Swift API.',
      '- A robust incremental parser design: header accumulation, Content-Length body, interleaved',
      '  packets arriving mid-header, oversized-header protection, and the exact error cases.',
    ].join('\n'),
  },
  {
    key: 'rtp',
    path: 'docs/spec-rtp.md',
    task: [
      'Author the RTP/RTCP and depacketization specification (module VigilRTP).',
      'Cover:',
      '- RTP fixed header (RFC 3550) with a bit/byte layout table, CSRC list, header extension',
      '  (0xBEDE one-byte form and the 0x1000 two-byte form), and padding handling.',
      '- **H.264 depacketization (RFC 6184)**: single NAL, STAP-A (mention STAP-B/MTAP), FU-A reassembly',
      '  with the exact FU indicator/header bit math to rebuild the original NAL header, handling of a',
      '  lost first or last fragment, and DON.',
      '- **H.265 depacketization (RFC 7798)**: the 2-byte PayloadHdr layout (F, Type, LayerId, TID),',
      '  AP aggregation packets, FU with S and E bits, DONL when sprop-max-don-diff is greater than 0;',
      '  how to detect VPS/SPS/PPS (types 32/33/34), IRAP types (16..23) and slice types (0..21).',
      '- **AAC (RFC 3640, mode=AAC-hbr)**: the AU-header-Length prefix, sizeLength / indexLength /',
      '  indexDeltaLength taken from the fmtp config, multi-AU packets, and how to build ADTS or an',
      '  AudioSpecificConfig from a hex config string such as config=1210. Handle the case-insensitivity',
      '  of mpeg4-generic vs MPEG4-GENERIC.',
      '- **G.711 PCMA/PCMU (payload types 8 and 0)** and G.726 as used by Hikvision two-way audio;',
      '  give the mu-law and A-law to linear PCM conversion approach.',
      '- Frame-boundary detection: the RTP marker bit versus timestamp change, and the correct rule for',
      '  H.264/H.265 access-unit boundaries (first_mb_in_slice == 0 /',
      '  first_slice_segment_in_pic_flag). Implement AU splitting that does NOT rely solely on the',
      '  marker bit, because some Hikvision firmware sets it unreliably. This is important - be explicit.',
      '- **Reorder/jitter buffer**: a bounded sequence-number-ordered ring with 16-bit wraparound-safe',
      '  comparison (give the seqLess helper), depth configurable in packets AND milliseconds,',
      '  late/duplicate/lost accounting, an onGap hook that requests an IDR, and a low-latency mode that',
      '  flushes immediately while packets are in order.',
      '- Timestamp math: the 90 kHz video clock mapped to MediaTimestamp (define it as a struct with an',
      '  Int64 value and an Int32 timescale), wraparound across 2^32, RTCP SR NTP-to-RTP mapping to',
      '  derive wall-clock time, and the drift-correcting presentation clock (describe the EWMA/PLL).',
      '- RTCP: parse SR / RR / SDES / BYE, generate a Receiver Report with fraction-lost and interarrival',
      '  jitter per RFC 3550 appendix A.8 (give the jitter formula), RTCP interval rules, and note that',
      '  interleaved channel 1 carries RTCP.',
      '- Statistics: define a StreamStatistics struct (fps, kbps EWMA, packets lost, out-of-order,',
      '  jitter in ms, keyframe interval, decode queue depth, dropped frames, latency estimate) and the',
      '  exact update algebra including the EWMA constants.',
      '- The public API: a Depacketizer protocol with a mutating push(packet) returning frames, and the',
      '  EncodedFrame definition (Foundation-only: data as 4-byte-length-prefixed NALs, pts, dts,',
      '  isKeyframe, codec, parameterSets).',
    ].join('\n'),
  },
  {
    key: 'bitstream',
    path: 'docs/spec-bitstream.md',
    task: [
      'Author the video bitstream specification (module VigilBitstream).',
      'Cover:',
      '- A rigorous **RBSP bit reader**: emulation-prevention byte (0x000003) removal, ue(v) and se(v)',
      '  Exp-Golomb, u(n), byte alignment, bounds checking. Give the exact Swift implementation.',
      '- **H.264 SPS parsing** (ITU-T H.264 section 7.3.2.1) end to end: profile_idc, constraint flags,',
      '  level_idc, seq_parameter_set_id, chroma_format_idc with separate_colour_plane_flag, bit depths,',
      '  scaling lists (which must be SKIPPED correctly - give the loop), log2_max_frame_num_minus4,',
      '  pic_order_cnt_type including type 1 cycle arrays, num_ref_frames, pic_width_in_mbs_minus1,',
      '  pic_height_in_map_units_minus1, frame_mbs_only_flag, mb_adaptive_frame_field_flag, frame',
      '  cropping offsets, and VUI (aspect-ratio idc table, timing_info num_units_in_tick and time_scale',
      '  giving fps, bitstream_restriction) - then derive the **exact display width, height, SAR and fps**.',
      '- **H.264 PPS**: the minimal parse we need, and an explicit statement of what we skip and why.',
      '- **H.265 parsing** (ITU-T H.265 section 7.3.2): the 2-byte NAL header, VPS (enough to store and',
      '  re-emit), SPS with the full profile_tier_level parse including sub-layer loops,',
      '  chroma_format_idc, pic_width_in_luma_samples and pic_height_in_luma_samples, conformance-window',
      '  offsets multiplied by SubWidthC/SubHeightC, log2 CTB size fields, and the short-term and',
      '  long-term reference picture sets which must be skipped correctly (give the st_ref_pic_set loop),',
      '  plus VUI timing giving fps.',
      '- **Format-record construction**: the exact byte layout of avcC (AVCDecoderConfigurationRecord,',
      '  including the 3-byte profile/compatibility/level, lengthSizeMinusOne = 3, numOfSPS and numOfPPS,',
      '  and the trailing extension for profiles 100/110/122/144) and of hvcC',
      '  (HEVCDecoderConfigurationRecord: configurationVersion, general_profile_space/tier/idc,',
      '  32-bit compatibility flags, 48-bit constraint indicator flags, level_idc,',
      '  min_spatial_segmentation_idc, parallelismType, chromaFormat, bit depths, avgFrameRate,',
      '  constantFrameRate + numTemporalLayers + temporalIdNested + lengthSizeMinusOne, numOfArrays and',
      '  the VPS/SPS/PPS/SEI arrays). Give hex-annotated worked examples of both.',
      '- Note that on macOS we can build a CMVideoFormatDescription either from these records or via',
      '  CMVideoFormatDescriptionCreateFromH264ParameterSets and',
      '  CMVideoFormatDescriptionCreateFromHEVCParameterSets. Specify which we use and why (prefer the',
      '  ParameterSets APIs at runtime; keep the record builders for MP4 muxing/recording and for tests).',
      '- Annex-B to 4-byte-length-prefixed conversion and back, in place where possible; a fast',
      '  start-code scanner; NAL type tables for both codecs; the SEI messages we care about (recovery',
      '  point, picture timing) and how to detect a stream that starts mid-GOP so we can drop frames',
      '  until the first IRAP.',
      '- The complete public Swift API, plus a list of **unit-test vectors**: real base64 SPS strings from',
      '  Hikvision cameras with the expected parsed values, that implementers must add as tests.',
    ].join('\n'),
  },
  {
    key: 'isapi',
    path: 'docs/spec-isapi.md',
    task: [
      'Author the Hikvision ISAPI integration specification (module VigilISAPI). This is the control',
      'plane of the app. For EVERY endpoint give: HTTP method, path, auth, request XML, response XML,',
      'the Swift model type it decodes to, and the error codes.',
      'Cover:',
      '- Device identity and capability: GET /ISAPI/System/deviceInfo, /ISAPI/System/capabilities,',
      '  /ISAPI/System/status, /ISAPI/System/time, /ISAPI/System/Network/interfaces,',
      '  /ISAPI/Security/userCheck (the cheap credential probe - describe its response and the',
      '  lock-out / retry fields), /ISAPI/ContentMgmt/InputProxy/channels (NVR IP channels) and',
      '  /ISAPI/System/Video/inputs/channels.',
      '- Streaming config: GET and PUT /ISAPI/Streaming/channels and /ISAPI/Streaming/channels/{id}',
      '  (read resolution, bitrate, fps, codec, GOP; and how to change substream settings), how channel',
      '  IDs map to RTSP paths, and',
      '  /ISAPI/Streaming/channels/{id}/picture?videoResolutionWidth=&videoResolutionHeight= for JPEG',
      '  snapshots - this is the fast path for grid thumbnails and sidebar previews.',
      '- **PTZ**: PUT /ISAPI/PTZCtrl/channels/{ch}/continuous with a PTZData body carrying pan, tilt and',
      '  zoom in the range -100..100; /momentary with a duration; /absolute with elevation, azimuth and',
      '  absoluteZoom; /relative; /presets/{n}/goto; GET /presets; PUT /presets/{n} to set;',
      '  /patrols and /patrols/{n}/start and /stop; /homeposition/goto; /PTZCtrl/channels/{ch}/status;',
      '  /capabilities; and 3D positioning PUT /ISAPI/PTZCtrl/channels/{ch}/position3D with the XY box,',
      '  which powers drag-to-zoom directly on the video. Give ranges, units, and the required',
      '  Content-Type: application/xml.',
      '- **Events**: GET /ISAPI/Event/notification/alertStream - the long-lived multipart/mixed stream.',
      '  Give a realistic sample showing the boundary, an application/xml part with',
      '  EventNotificationAlert (eventType values VMD, linedetection, fielddetection, regionEntrance,',
      '  facedetection, tamperdetection, io, videoloss, diskfull; eventState, channelID, dateTime,',
      '  activePostCount, and the DetectionRegionList polygon) and an image/jpeg part for event',
      '  snapshots. Specify a streaming multipart parser design that never buffers unbounded data, plus',
      '  the reconnect policy. Also /ISAPI/Event/triggers, /ISAPI/Event/schedules, and motion-detection',
      '  config at /ISAPI/System/Video/inputs/channels/{ch}/motionDetection.',
      '- **Recorded video (playback)**: POST /ISAPI/ContentMgmt/search with a CMSearchDescription',
      '  (searchID GUID, trackIDList, timeSpanList start and end, maxResults, searchResultPostion for',
      '  paging - note the real misspelling - and metadataList) returning CMSearchResult with',
      '  matchList / searchMatchItem / trackID, timeSpan, mediaSegmentDescriptor with contentType,',
      '  codecType and playbackURI. Show the playbackURI form',
      '  rtsp://host/Streaming/tracks/101?starttime=...&endtime=...&name=...&size=...',
      '  Also /ISAPI/ContentMgmt/record/tracks, storage at /ISAPI/ContentMgmt/Storage (HDD/SD status,',
      '  capacity, quota) and the day-level calendar query used to paint the timeline heatmap - specify',
      '  exactly which endpoint we use for the timeline UI and its response shape.',
      '- **Two-way audio**: GET /ISAPI/System/TwoWayAudio/channels, PUT .../{id}/open,',
      '  POST .../{id}/audioData (chunked G.711 upload), and .../close. Include the codec negotiation.',
      '- Image settings: PUT /ISAPI/Image/channels/{ch}/... (brightness, contrast, saturation, sharpness,',
      '  WDR, IR-cut, day/night), plus reboot, /ISAPI/Security/users, and NVR-specific',
      '  /ISAPI/ContentMgmt/InputProxy/channels/{id}/status.',
      '- Error handling: the ResponseStatus body with statusCode and subStatusCode values such as',
      '  notSupport, badParameters, deviceBusy, invalidOperation - and how each maps to a user-facing',
      '  message.',
      '- A robust **lenient XML decoder**: XMLParser-based, namespace-agnostic, path-keyed, tolerant of',
      '  unknown elements and of differing firmware casings, because Hikvision XML varies wildly by',
      '  firmware. Give its full API and explain why we do not use Codable XML.',
      '- HTTP client requirements: Digest auth, connection reuse, per-request timeouts, cancellation,',
      '  plain http on LAN, accepting self-signed TLS for https, and a per-device concurrency limit.',
    ].join('\n'),
  },
  {
    key: 'discovery',
    path: 'docs/spec-discovery.md',
    task: [
      'Author the camera discovery specification (module VigilDiscovery plus macOS transport notes).',
      'Cover three mechanisms in the order we run them, with exact wire formats:',
      '1) **Hikvision SADP**: UDP multicast to 239.255.255.250 port 37020 from a local port (37020',
      '   preferred), the Probe payload carrying a Uuid and Types=inquiry, and the ProbeMatch response',
      '   fields (Types, DeviceType, DeviceDescription, DeviceSN, CommandPort, HttpPort, MAC,',
      '   IPv4Address, IPv4SubnetMask, IPv4Gateway, IPv6Address, DSPVersion, BootTime, Activated,',
      '   PasswordResetAbility, SupportHCPlatform). Give a realistic sample response XML. Note that',
      '   Activated=false means the camera needs activation and we must surface that in the UI. Note the',
      '   newer obfuscated SADP variants and how we degrade gracefully.',
      '2) **ONVIF WS-Discovery**: UDP multicast to 239.255.255.250 port 3702, the exact SOAP 1.2 Probe',
      '   envelope including a NetworkVideoTransmitter type and a uuid MessageID, and parsing',
      '   ProbeMatches for XAddrs and Scopes (extract the onvif.org name, hardware and location scopes).',
      '   Specify the retry policy (3 probes 500 ms apart) and note that responses arrive from arbitrary',
      '   source ports so we must listen on the sending socket.',
      '3) **Targeted subnet sweep**: enumerate local IPv4 interfaces and netmasks (getifaddrs in the',
      '   macOS layer, pure CIDR maths in the module, with a guard that refuses to sweep prefixes wider',
      '   than /16), then concurrent TCP connect probes to ports 554, 80, 8000, 443, 8080 with a tight',
      '   350 ms timeout and bounded concurrency of about 128 in flight, then an RTSP OPTIONS plus an',
      '   HTTP GET /ISAPI/System/deviceInfo fingerprint to classify Hikvision versus other (also detect',
      '   Dahua and Axis so we can tell the user "found, but not Hikvision"). Include reading the ARP',
      '   cache as a shortcut, and an NWBrowser Bonjour browse of _rtsp._tcp and _http._tcp.',
      'Then specify: the **merge and dedupe model** (identity = MAC, else serial, else ip:port; how',
      'records from multiple sources merge; how we detect a camera whose IP changed), the',
      'DiscoveredDevice value type, progress reporting for the UI (found count, swept count, ETA),',
      'cancellation, and the required macOS entitlements and Info.plist keys for multicast',
      '(com.apple.developer.networking.multicast plus NSLocalNetworkUsageDescription) and exactly what',
      'happens if the multicast entitlement is absent (fall back to the unicast sweep) - spell out the',
      'user-facing consequence and the local-network permission prompt flow, this matters a lot.',
      'Give the full public Swift API and a set of unit tests driven by recorded packet bytes.',
    ].join('\n'),
  },
  {
    key: 'video',
    path: 'docs/spec-video-pipeline.md',
    task: [
      'Author the decode and playback pipeline specification (module VigilVideo).',
      'Cover:',
      '- Constructing CMVideoFormatDescription from SPS/PPS and VPS via',
      '  CMVideoFormatDescriptionCreateFromH264ParameterSets and',
      '  CMVideoFormatDescriptionCreateFromHEVCParameterSets - exact signatures, pointer handling with',
      '  nested withUnsafeBufferPointer over an array of pointers, and nalUnitHeaderLength 4.',
      '- Wrapping length-prefixed NAL data into a CMBlockBuffer and CMSampleBuffer with correct',
      '  CMSampleTimingInfo (duration, pts, dts), the NotSync sample attachment for non-keyframes, and',
      '  the DisplayImmediately attachment for low latency.',
      '- Two display strategies and when each is used:',
      '  (a) **AVSampleBufferDisplayLayer** with requiresFlushToResumeDecoding, a control timebase versus',
      '      immediate mode, and its automatic hardware decode - the default fast path;',
      '  (b) an explicit **VTDecompressionSession** producing CVPixelBuffers rendered with **Metal** -',
      '      used when we need pixel access (digital-zoom shader, snapshots, motion overlay, colour',
      '      grading, video-wall compositing).',
      '  Specify the VTDecompressionSessionCreate attributes: EnableHardwareAcceleratedVideoDecoder,',
      '  RealTime, MaximizePowerEfficiency, ThreadCount, output pixel format',
      '  420YpCbCr8BiPlanarVideoRange (and 420YpCbCr10BiPlanarVideoRange for HEVC Main10),',
      '  MetalCompatibility and IOSurfaceProperties keys, and a CVPixelBufferPool. Also the decode flags',
      '  EnableAsynchronousDecompression and 1xRealTimePlayback, and how to handle',
      '  kVTVideoDecoderBadDataErr, kVTInvalidSessionErr and kVTVideoDecoderMalfunctionErr (recreate the',
      '  session, then wait for an IDR).',
      '- **Mid-stream format changes** (a new SPS with a different resolution): detect, drain, recreate',
      '  the session without dropping the window or flashing black.',
      '- **Low-latency live clock**: no A/V sync buffering for live, render on decode, display',
      '  immediately, a bounded 2-3 frame queue, drop-to-keyframe when behind, and an adaptive latency',
      '  controller that measures queue depth over a sliding window. Give the exact thresholds.',
      '- **Recorded playback**, which is different: a real timebase, PTS-ordered reordering for B-frames',
      '  and POC reorder, pause, seek, scale 0.25x to 8x, reverse, and single-frame step.',
      '- **Decode-budget scheduler**: a global actor that admits decode sessions by cost',
      '  (resolution x fps x codec weight) because macOS has a finite number of hardware decode',
      '  sessions. Give the policy for a 16-up grid (substreams only; and when a tile is smaller than a',
      '  threshold use the ISAPI JPEG snapshot refresh instead of decoding at all - give the exact pixel',
      '  thresholds and refresh intervals), pausing decode for offscreen, occluded or minimized tiles',
      '  via NSWindow.occlusionState, and dropping to keyframe-only below a size threshold.',
      '- **Audio**: AVAudioEngine plus an AVAudioSourceNode fed from AAC (decoded with AudioConverter /',
      '  AudioToolbox) or G.711 (table lookup), per-camera mute and solo, and the rule that audio is',
      '  enabled only for the focused camera by default. Include the two-way-audio capture path',
      '  (AVAudioEngine input -> G.711 encode -> ISAPI upload) and push-to-talk semantics.',
      '- Snapshot capture: CVPixelBuffer to CGImage via VTCreateCGImageFromCVPixelBuffer or CIContext,',
      '  then PNG/JPEG/HEIC write with metadata.',
      '- Hardware and energy notes: how to verify hardware decode is actually engaged, expected CPU and',
      '  GPU numbers, thermal and low-power-mode adaptation, and the design of a benchmark harness.',
      '- The full public Swift API (actor DecodePipeline, protocol VideoSink, and friends) and the exact',
      '  error handling.',
    ].join('\n'),
  },
  {
    key: 'render',
    path: 'docs/spec-render.md',
    task: [
      'Author the rendering and on-video interaction specification (module VigilRender).',
      'Cover:',
      '- The VideoTileView: an NSView backed by either AVSampleBufferDisplayLayer or CAMetalLayer,',
      '  wrapped for SwiftUI via NSViewRepresentable. Get the details right: wantsLayer,',
      '  layerContentsRedrawPolicy, updating layer.contentsScale when the backing display changes,',
      '  videoGravity, and how to avoid the classic AppKit resize flicker (CATransaction with actions',
      '  disabled, NSView.inLiveResize, an opaque layer-backed background).',
      '- The **Metal renderer**: one shared MTLDevice and MTLCommandQueue app-wide; a CVMetalTextureCache',
      '  for zero-copy CVPixelBuffer to MTLTexture conversion for both planes of a biplanar buffer; the',
      '  YCbCr to RGB conversion matrices (BT.709 video-range and full-range, and BT.2020 for 10-bit',
      '  HEVC) applied in the fragment shader; a vertex shader with a model matrix for **digital zoom and',
      '  pan** up to 8x with inertial motion; and optional post effects: sharpen, brightness, contrast,',
      '  gamma, deinterlace (bob and blend, for interlaced analog NVR channels) and a night-boost tone',
      '  curve. Provide the ACTUAL Metal shader source for the YUV-to-RGB plus transform plus adjustment',
      '  pass, and the pipeline-state setup code. Specify triple buffering, presentsWithTransaction for',
      '  glitch-free resize, maximumDrawableCount, displaySyncEnabled, and using the macOS 14',
      '  NSView displayLink API for pacing on ProMotion displays.',
      '- **Overlays**: decide and justify which are drawn as SwiftUI on top versus inside Metal:',
      '  timestamp OSD, camera-name chip, recording indicator, motion boxes from ISAPI events mapped',
      '  from the camera 0..1000 normalized coordinate space into view space (spell out the transform,',
      '  including the inverted Y axis some firmware uses), privacy-mask preview, PTZ direction',
      '  indicator, and the drag rectangle for 3D-positioning PTZ.',
      '- **Interactions**: scroll-to-zoom anchored at the cursor, two-finger pan, pinch magnify via',
      '  NSMagnificationGestureRecognizer, double-click to fullscreen with a matched-geometry-style',
      '  transition, right-click context menu, drag-and-drop of a tile between grid cells with a live',
      '  ghost image, dragging a camera from the sidebar onto a cell, arrow keys driving PTZ when a tile',
      '  is focused, and precise cursor changes.',
      '- **Video-wall compositing**: whether N tiles share one Metal layer or get one layer each. Make',
      '  the decision (one CAMetalLayer per tile up to K tiles, single-layer atlas compositing above K)',
      '  with the rationale, and explain how we hold 120 Hz with 16 tiles.',
      '- HDR and EDR notes, colour-space tagging (CAMetalLayer colorspace,',
      '  wantsExtendedDynamicRangeContent), and correct behaviour across multiple displays with',
      '  different scale factors.',
      '- An AVSampleBufferDisplayLayer-only fallback path for machines where Metal initialisation fails.',
      '- The full public Swift API and a checklist of visual-correctness tests: aspect ratio with',
      '  non-square pixels (SAR), the cropping window, the 1088-versus-1080 crop, interlaced content,',
      '  and 10-bit content.',
    ].join('\n'),
  },
  {
    key: 'design',
    path: 'docs/DESIGN.md',
    task: [
      'Author the **design system** for Vigil. This is the most important document for how the app',
      'feels - the top requirement from the customer is a stunning, modern, top-tier Mac design with',
      'rich animation. Act as a world-class product designer and be extremely specific.',
      'Cover:',
      '- **Design thesis** in five sentences: what Vigil looks and feels like (a calm, dark,',
      '  cinema-grade surveillance cockpit where the video is the hero and the chrome dissolves away),',
      '  and the six principles that follow from it.',
      '- **Colour**: a complete token set in both dark (primary) and light appearance. Give exact sRGB',
      '  hex values AND the SwiftUI Color initialiser expression for each. Layers: canvas, sidebar',
      '  (vibrancy), surface, surface-raised, overlay; strokes subtle / default / strong; text primary /',
      '  secondary / tertiary / inverse. Semantic: accent (choose a distinctive non-default accent and',
      '  argue for it), accent-pressed, live (recording red), ok, warn, danger, motion (event',
      '  highlight). Plus a six-colour categorical palette for camera identity chips that is',
      '  colour-blind safe. Specify when to use NSVisualEffectView materials (sidebar, headerView,',
      '  hudWindow, underWindowBackground) versus solid fills, and the rule that video tiles are always',
      '  true black.',
      '- **Typography**: SF Pro Text / SF Pro Display / SF Mono usage; a nine-step scale with size,',
      '  weight, line height and tracking for each step (Display, Title1-3, Headline, Body, Callout,',
      '  Caption1-2, Mono); the rule that every changing number uses monospacedDigit; and the exact',
      '  SwiftUI Font expressions.',
      '- **Space and shape**: a 4pt base grid with named steps, a radius scale (4/6/8/10/14/20/full) and',
      '  the rule for nesting radii, border widths, and the standard control heights (20/24/28/32/40).',
      '- **Elevation and materials**: four elevation levels each defined as a quadruple of fill, stroke,',
      '  inner highlight and shadow, with exact shadow specs; and the "glass" recipe (material plus a',
      '  1px top inner highlight at 8% white plus a hairline stroke) used for floating toolbars and the',
      '  command palette.',
      '- **Motion** - this is critical. Define a motion vocabulary with exact SwiftUI values, for example',
      '  micro = spring(response 0.22, dampingFraction 0.86), standard = spring(0.34, 0.82),',
      '  expressive = spring(0.5, 0.7), plus entrance and exit curves and easing for non-spring cases.',
      '  Then specify per interaction exactly what animates: sidebar reveal; grid layout change using',
      '  matchedGeometryEffect between a grid cell and fullscreen; tile appearance (scale 0.96 to 1 plus',
      '  opacity with an 18 ms stagger); connection state (skeleton shimmer into a first-frame crossfade);',
      '  the live-dot pulse (2 s ease-in-out breathing); PTZ press feedback; command-palette open',
      '  (scale 0.97 to 1 with material blur-in over 180 ms); toast slide-in; timeline scrub magnetism;',
      '  hover elevation lift; focus-ring animation; and the loading choreography for a 16-tile grid.',
      '  Include PhaseAnimator, KeyframeAnimator and transaction usage notes, reduceMotion fallbacks for',
      '  EVERY animation, and the hard rule that we never animate anything that would drop the video',
      '  below 60 fps - overlays animate on the compositor, never by re-laying-out video layers.',
      '- **Iconography**: a table of every action in the app mapped to an SF Symbol name plus variant and',
      '  weight, rules for symbol rendering modes, and the two custom symbols we need.',
      '- **Component inventory** with visual specs and all states (rest, hover, pressed, focused,',
      '  disabled, loading) for: VButton (primary, secondary, ghost, destructive, icon),',
      '  VSegmentedControl, VToggle, VSlider, VTextField with inline validation, VSearchField, VSelect,',
      '  VBadge, VChip, VCard, VToolbar (floating glass), VSidebarRow (with live thumbnail and status',
      '  dot), VTile (the video cell: chrome on hover, corner radius, focus ring, name chip, stats HUD),',
      '  VTimeline (recording scrubber with heatmap), VPTZPad (joystick), VCommandPalette, VToast,',
      '  VEmptyState, VSkeleton, VStatPill, VSparkline, VContextMenu, VPopover, VSheet,',
      '  VInspectorSection, VKeyCap.',
      '- **Accessibility**: the contrast ratios met (state the numbers), full keyboard operability,',
      '  VoiceOver labels for video tiles and PTZ, increaseContrast and differentiateWithoutColor',
      '  handling, and minimum hit-target sizes.',
      '- **App icon and window chrome**: describe the icon concept concretely, the title-bar treatment',
      '  (hiddenTitleBar window style, unified toolbar, traffic-light inset), and the fullscreen',
      '  "cinema mode" chrome.',
      'Deliver a spec an implementer can build pixel-accurately, and sketch the structure of the SwiftUI',
      'token file (an enum VTheme with nested namespaces).',
    ].join('\n'),
  },
  {
    key: 'ux',
    path: 'docs/UX.md',
    task: [
      'Author the UX, information-architecture and interaction specification for Vigil.',
      'Cover:',
      '- **App structure**: a single main window with three regions (sidebar / stage / inspector), plus',
      '  auxiliary windows (Settings, Discovery, Playback, Video Wall on a second display, About).',
      '  Specify the SwiftUI WindowGroup / Window / Settings scenes, window sizing and restoration, and',
      '  the NavigationSplitView configuration.',
      '- **Sidebar**: sections (Live, Groups, Cameras, Recordings, Events, Bookmarks); each camera row',
      '  shows a live micro-thumbnail, name, a status dot (connecting / live / degraded / offline), a',
      '  codec and resolution badge, and a motion-activity spark; drag to reorder and to group; a',
      '  context menu; inline rename; search and filter; and collapse to an icon-only rail.',
      '- **Stage**: layout modes 1, 2x2, 1+5, 3x3, 4x4, 1+7, 2+8 and a custom drag-resizable mosaic;',
      '  per-cell camera assignment by drag and drop; a cycle/patrol mode that rotates cameras on a',
      '  timer; fullscreen single camera; picture-in-picture; a second-display video wall; per-tile hover',
      '  chrome (mute, snapshot, record, PTZ, fullscreen, substream/mainstream toggle, aspect fit or',
      '  fill, close); double-click to zoom; scroll to digital-zoom; and keyboard navigation between',
      '  tiles.',
      '- **Inspector** (right panel) tabs: Info (device, firmware, serial, uptime, storage); Stream',
      '  (codec, resolution, fps, bitrate live sparklines, packet loss, jitter, decode queue, latency',
      '  estimate, hardware-decode indicator); PTZ (pad, zoom/focus/iris, a presets grid with thumbnails,',
      '  patrols, home); Image (brightness, contrast, saturation, sharpness, WDR, day/night, IR);',
      '  Events (recent motion list with thumbnails); Recording (schedule and storage).',
      '- **Playback**: a dedicated timeline experience - a date picker plus a 24-hour horizontal timeline',
      '  per camera with a recording-density heatmap (motion amber, continuous blue, alarm red);',
      '  pinch or scroll to zoom the timeline from 24 hours down to one minute; drag to scrub with live',
      '  preview thumbnails; transport controls (play/pause, minus and plus 10 s, frame step, speed',
      '  0.25x to 8x, reverse); multi-camera synchronized playback; in and out point selection with clip',
      '  export as MP4 passthrough; and an instant "go to this moment" jump from an event.',
      '- **Discovery / add camera**: the onboarding flow - a scan animation with devices appearing, a',
      '  manual-add form (host, ports, credentials, channel, transport), a credential test with clear',
      '  distinct failure reasons (wrong password vs locked out vs unreachable vs not-Hikvision), an',
      '  auto-detected channel list for NVRs with checkboxes, bulk add, and CSV import.',
      '- **Events**: a unified event feed (motion, line crossing, intrusion, tamper, video loss, disk',
      '  error) with thumbnails, filters and click-to-playback; local notifications; and a watch mode',
      '  that raises a toast or overlay on motion.',
      '- **Command palette (Cmd-K)**: fuzzy actions - jump to camera, switch layout, start/stop',
      '  recording, snapshot all, PTZ preset, open settings, toggle audio. Specify the ranking algorithm',
      '  and the anatomy of a result row.',
      '- **Keyboard shortcuts**: a COMPLETE table (Cmd-1..9 layouts, Cmd-F fullscreen, Space play/pause,',
      '  Cmd-R record, Cmd-Shift-S snapshot, Cmd-K palette, Cmd-L sidebar, Cmd-Opt-I inspector, arrows',
      '  PTZ, Opt-arrows tile navigation, Cmd-comma settings, Cmd-E export, slash search, Esc exit,',
      '  Cmd-Ctrl-F cinema) plus the menu-bar structure (App, File, View, Camera, Playback, Window,',
      '  Help) mirroring every one of them.',
      '- **States**: first run, no cameras, scanning, connecting (skeleton plus progress narration),',
      '  degraded (packet-loss banner), offline (retry countdown with the last-known frame dimmed), auth',
      '  failure, storage full, app in background, and sleep/wake plus network-change recovery.',
      '- **Settings**: General (launch at login, appearance, units, time format); Streams (default',
      '  transport TCP or UDP, substream in grid, latency preset low/balanced/quality, hardware decode',
      '  toggle, max concurrent decodes); Recording (folder, format, pre and post buffer, auto-record on',
      '  motion, retention); Notifications; Shortcuts (rebindable); Advanced (log level, export',
      '  diagnostics, reset); About and updates.',
      '- **Copy and tone**: the writing rules, plus the exact strings for the 20 most important messages',
      '  (errors, empty states, confirmations) - concise, human, no jargon dumps. Give them in English,',
      '  and note that a Russian localization is required so keys must be structured for it.',
      '- **Latency-perception rules**: exactly what we show in the first 100 ms, 300 ms and 1000 ms of a',
      '  connection so it always feels instant; and optimistic UI for PTZ and settings changes.',
      'Include ASCII wireframes for the main window, the playback view and the discovery sheet.',
    ].join('\n'),
  },
  {
    key: 'features',
    path: 'docs/FEATURES.md',
    task: [
      'Author the complete, prioritized feature specification for Vigil - the definitive scope document.',
      'Structure it as P0 (must ship), P1 (ship if time) and P2 (future). Be generous but honest about',
      'P0, because the customer explicitly asked for deep, complete, fully worked-out functionality.',
      'For every feature give: a one-line description, testable acceptance criteria, the modules it',
      'touches, and the risk.',
      'Cover at minimum: multi-camera live view with all layout modes; automatic and manual camera',
      'discovery with an activation warning; secure credential storage; H.264, H.265 and MJPEG support;',
      'TCP and UDP RTSP transports; main/sub stream switching driven automatically by tile size;',
      'hardware-accelerated decode with a visible indicator; audio playback with per-camera mute plus',
      'two-way audio push-to-talk; digital zoom and pan; full PTZ (continuous, presets, patrols,',
      '3D-positioning drag, focus, iris, speed control); snapshots (single and all cameras) with',
      'configurable format and destination plus copy-to-clipboard; manual recording to MP4 with',
      'passthrough muxing and a configurable pre-roll buffer; motion-triggered local recording;',
      'NVR/DVR channel enumeration; recorded-video search and timeline playback with speed control and',
      'clip export; synchronized multi-camera playback; the event/alarm stream with notifications and an',
      'event feed; image settings control; camera health monitoring (fps, bitrate, loss, jitter, latency,',
      'uptime) with history graphs and alerting on stream loss; auto-reconnect with backoff;',
      'network-change and sleep/wake resilience; layouts saved as named presets; camera groups; a camera',
      'cycling view; a second-display video wall; picture-in-picture; a menu-bar extra with quick access',
      'and a live badge; the command palette; global keyboard shortcuts; deep links using a vigil URL',
      'scheme; AppleScript and Shortcuts automation via App Intents; CSV and JSON import/export of camera',
      'configuration; encrypted config export; a diagnostics-bundle export; localization scaffolding for',
      'English and Russian with the Russian strings actually written; light/dark/auto appearance; full',
      'accessibility (keyboard and VoiceOver); crash-free reconnect after a camera reboot; an ONVIF',
      'fallback for non-Hikvision devices; and an in-app "Stream Doctor" that diagnoses why a camera will',
      'not connect (port closed, auth failure, unsupported codec, wrong RTSP path, multicast blocked)',
      'with actionable fixes.',
      'Add a **Non-goals** section (cloud, P2P / Hik-Connect, mobile, transcoding server, face',
      'recognition) and say why.',
      'Add a **Performance budget** section with hard numbers (cold launch to first frame, glass-to-glass',
      'latency by transport, CPU/GPU/memory per stream and for 16 streams, UI frame time p99, memory',
      'ceiling, energy impact) and exactly how each is measured.',
      'Add a **Security and privacy** section: credentials in Keychain only and never in the config JSON;',
      'no telemetry; LAN-only outbound traffic; how we handle plain http and self-signed TLS; and what we',
      'log versus redact (mask passwords, session ids and camera serials in logs).',
    ].join('\n'),
  },
  {
    key: 'core',
    path: 'docs/spec-core.md',
    task: [
      'Author the application-domain specification (module VigilCore) - the layer between the protocol',
      'modules and the UI. Give complete public Swift API signatures for every type.',
      'Cover:',
      '- **Domain model**: Camera (id UUID, name, host, httpPort, rtspPort, useTLS, channel,',
      '  streamProfile, transport, credentialRef, groupID, orderIndex, capabilities snapshot, createdAt,',
      '  lastSeenAt, colorTag, isEnabled), CameraGroup, Layout (mode plus a cell-to-camera map),',
      '  Bookmark, EventRecord, RecordingClip, DeviceCapabilities, StreamProfile (main/sub/third with',
      '  resolved codec, resolution, fps, bitrate). All Sendable and Codable with stable coding keys and',
      '  a schemaVersion.',
      '- **Persistence**: ConfigStore - a single JSON document at',
      '  ~/Library/Application Support/Vigil/library.json, atomic write via a temp file and',
      '  FileManager.replaceItemAt, debounced saves coalescing over 500 ms, .bak rotation, a schema',
      '  migration chain, and corruption recovery. Justify why not SwiftData or CoreData (predictable,',
      '  diffable, exportable, no store-migration risk) and state what we would change past 10k records.',
      '- **Credentials**: CredentialStore on the Keychain - kSecClassInternetPassword with server, port,',
      '  account and path attributes, kSecAttrAccessibleWhenUnlocked, exact SecItemAdd / SecItemCopyMatching',
      '  / SecItemUpdate / SecItemDelete code with OSStatus error mapping, an in-memory cache, a Sendable',
      '  Credential value type, and the hard rule that credentials never enter logs or the JSON.',
      '- **StreamController** (one per active camera): an actor owning the RTSP session, depacketizer and',
      '  decode pipeline. Public API: start, stop, setQuality(main/sub/auto), requestKeyframe,',
      '  snapshot() async throws, startRecording, and an AsyncStream of StreamEvent. Give the internal',
      '  state machine (idle, resolving, connecting, authenticating, describing, settingUp, playing,',
      '  degraded, reconnecting, failed, stopped) with the FULL transition table, per-state timeouts, and',
      '  the reconnect policy (backoff 0.5, 1, 2, 4, 8, 15, 30 s capped, plus or minus 20% jitter, reset',
      '  after 60 s of health, immediate retry when the network comes back).',
      '- **StreamCoordinator**: app-wide orchestration - which cameras are live given the current layout,',
      '  the decode-budget admission policy, priority ordering (focused, then visible, then offscreen,',
      '  then sidebar thumbnail), pause-on-occlusion, resume-on-wake, an NWPathMonitor reaction, and a',
      '  global concurrency limiter. Give the exact policy table mapping tile pixel size to',
      '  main / sub / JPEG-poll / paused.',
      '- **Recording**: ClipRecorder using AVAssetWriter with an AVAssetWriterInput created with nil',
      '  output settings and a sourceFormatHint, for **passthrough** muxing of already-compressed samples',
      '  into MP4 or MOV with no re-encode. Handle the first-sample-must-be-a-keyframe rule, a pre-roll',
      '  ring buffer holding the last N seconds of compressed GOPs, timestamp rebasing so the file starts',
      '  at zero, audio track inclusion, a file-naming template, disk-space checks, graceful finish on',
      '  quit or crash (write to .partial then rename), and MP4 fragmentation for crash resilience.',
      '- **Snapshots**: from the render pipeline (the exact displayed frame) or via ISAPI JPEG (cheap);',
      '  PNG, JPEG and HEIC; EXIF metadata stamping with camera name and timestamp; an optional burn-in',
      '  overlay; and destinations including the clipboard and Quick Look.',
      '- **Events**: EventCenter consuming the ISAPI alertStream per device, dedupe and coalesce (same',
      '  eventType plus channel within 3 s), persistence of the last 5000 events, UNUserNotificationCenter',
      '  local notifications with a thumbnail attachment, and the motion-to-auto-record trigger with a',
      '  cooldown.',
      '- **Health and diagnostics**: HealthMonitor sampling each StreamController at 1 Hz into a',
      '  fixed-size 10-minute ring for the UI sparklines; the **Stream Doctor** diagnostic sequence',
      '  (TCP probe of 554 and 80, then RTSP OPTIONS, then DESCRIBE with auth, then an SDP codec check,',
      '  then a first-RTP-packet timeout, then a first-keyframe timeout) with the mapping from each',
      '  failure point to a user-facing cause and fix; and the diagnostics bundle contents (redacted',
      '  logs, config without secrets, SDP dumps, a stats CSV).',
      '- **App Intents, deep links and AppleScript**: the intent surface and the URL-scheme grammar.',
      '- The list of unit tests, with fakes for RTSP and ISAPI, that must accompany all of the above.',
    ].join('\n'),
  },
]

log('Phase 1 starting: ' + SPECS.length + ' spec authors in parallel. Live log: .build-progress.log')

const specResults = await parallel(SPECS.map((s) => () =>
  agent(
    SHARED +
      '\n\n---\n\n## YOUR ASSIGNMENT\n' +
      'AGENT_LABEL for your log lines is: spec:' + s.key + '\n' +
      'Write the file: /home/user/camera/' + s.path + '\n\n' +
      s.task +
      '\n\nCreate parent directories if needed. Be exhaustive and concrete.',
    { label: 'spec:' + s.key, phase: 'Specs', effort: 'high' }
  ).then((text) => ({ key: s.key, path: s.path, summary: text || '(no summary returned)' }))
))

const good = specResults.filter(Boolean)
log('Phase 1 complete: ' + good.length + '/' + SPECS.length + ' spec documents written')
if (good.length < SPECS.length) {
  const got = new Set(good.map((g) => g.key))
  log('MISSING specs: ' + SPECS.filter((s) => !got.has(s.key)).map((s) => s.key).join(', '))
}

phase('Contract')
log('Phase 2 starting: reconciling all specs into docs/API_CONTRACT.md (the load-bearing artifact)')

const digest = good.map((g) => '### ' + g.key + '  (' + g.path + ')\n' + g.summary).join('\n\n')

const contract = await agent(
  SHARED +
    '\n\n---\n\n## YOUR ASSIGNMENT - API CONTRACT AND FILE MANIFEST\n' +
    'AGENT_LABEL for your log lines is: contract\n\n' +
    'Twelve sibling agents have just written spec documents into /home/user/camera/docs/.\n' +
    'Here are their self-reported cross-cutting decisions:\n\n' +
    digest +
    '\n\n**Read all of those files yourself** (docs/ARCHITECTURE.md, docs/spec-rtsp.md, docs/spec-rtp.md,\n' +
    'docs/spec-bitstream.md, docs/spec-isapi.md, docs/spec-discovery.md, docs/spec-video-pipeline.md,\n' +
    'docs/spec-render.md, docs/DESIGN.md, docs/UX.md, docs/FEATURES.md, docs/spec-core.md). Skim every\n' +
    'one and read the API sections closely. Log after each file you read.\n\n' +
    'Then write /home/user/camera/docs/API_CONTRACT.md, the single source of truth that parallel\n' +
    'implementation agents will code against. It must:\n\n' +
    '1. **Reconcile conflicts.** Where two specs disagree on a type name, signature, module ownership or\n' +
    '   behaviour, YOU decide and state the ruling explicitly in a Rulings section (spec X said A,\n' +
    '   spec Y said B, we do B because ...). Be decisive.\n' +
    '2. Declare the **canonical shared value types** as verbatim Swift source (these live in\n' +
    '   VigilProtocols): MediaTimestamp, MediaInstant, EncodedFrame, VideoCodec, AudioCodec,\n' +
    '   ParameterSets, StreamQuality, RTSPTransportKind, StreamStatistics, VigilError (the unified error\n' +
    '   enum with every case), LogCategory / LoggerProtocol, ByteReader, ByteWriter, BitReader,\n' +
    '   Credential, IPv4Address, IPv4Subnet. Full declarations, not sketches - implementers paste these.\n' +
    '3. For **every module**, list the exact public API surface as Swift declarations (protocols, types,\n' +
    '   methods with full signatures, no bodies). This is the contract; nothing may be added to a\n' +
    "   module's public surface later without a note.\n" +
    '4. Provide the **complete file manifest**: every source file we will create, as a table of\n' +
    '   path | target | responsibility | approx LoC | depends on. Group by target. Include test files.\n' +
    '   It must be complete enough that 20 agents can each take a set of rows and produce compiling,\n' +
    '   fitting files. Expect roughly 130 to 190 files.\n' +
    '5. Provide the exact **Package.swift** content as a code block reflecting the manifest, with\n' +
    '   swift-tools-version 6.0, the macOS 14 platform, all targets, and the decided mechanism by which\n' +
    '   the pure targets and their tests build on Linux while macOS-only targets are excluded.\n' +
    '6. Provide **cross-cutting implementation rules** every agent must follow: file header comment\n' +
    '   format, public/package/internal policy, Swift 6 Sendable conformance rules, no force-unwraps,\n' +
    '   error-throwing style, logging via the injected LoggerProtocol in pure targets and OSLog in\n' +
    '   macOS targets, doc comments required on public API, MARK structure, 110-column lines, and the\n' +
    '   rule that pure targets must not import platform frameworks.\n' +
    '7. A **build and verification checklist**: the commands we run (swift build, swift test for the\n' +
    '   pure subset on Linux, xcodebuild on macOS, Scripts/build-app.sh) and what "done" means.\n\n' +
    'Be long and exhaustive. This document is the most load-bearing artifact in the project.\n' +
    'Write it with the Write tool. Return a summary of at most 25 lines of your rulings and target list.',
  { label: 'api-contract', phase: 'Contract', effort: 'max' }
)

log('Phase 2 complete: docs/API_CONTRACT.md written')

return { specs: good.map((g) => g.path), contract: contract || '(empty)' }
