#!/usr/bin/env swift

import Foundation

let arguments = Array(CommandLine.arguments.dropFirst())
if arguments.contains("--help") {
    print("Usage: Scripts/gen-shader-source.swift [SHADER_DIR] [OUTPUT]")
    exit(0)
}

let shaderDirectory = URL(fileURLWithPath: arguments.first ?? "Sources/VigilRender/Shaders")
let output = URL(
    fileURLWithPath: arguments.dropFirst().first ?? "Sources/VigilRender/Shaders/ShaderSource.swift"
)
let manager = FileManager.default
let files = try manager.contentsOfDirectory(at: shaderDirectory, includingPropertiesForKeys: nil)
    .filter { $0.pathExtension == "metal" }
    .sorted { $0.lastPathComponent < $1.lastPathComponent }

func literal(_ value: String) -> String {
    let hashes = String(repeating: "#", count: 1 + value.components(separatedBy: "\"\"\"").count)
    return "\(hashes)\"\"\"\n\(value)\n\"\"\"\(hashes)"
}

var generated = "// Generated by Scripts/gen-shader-source.swift. Do not edit.\n\n#if os(macOS)\n\n"
generated += "enum ShaderSource {\n"
for file in files {
    let name = file.deletingPathExtension().lastPathComponent
        .replacingOccurrences(of: "-", with: "_")
    let source = try String(contentsOf: file, encoding: .utf8)
    generated += "    static let \(name) = \(literal(source))\n"
}
generated += "}\n\n#endif  // os(macOS)\n"

let old = try? String(contentsOf: output, encoding: .utf8)
if old != generated {
    try generated.write(to: output, atomically: true, encoding: .utf8)
}
